### PR TITLE
Data formating issues Fixed #17

### LINKED ISSUE #17: Error 404 surfaces when loading
**Describe the bug**
The 404 is displayed in data spots when the pages first load. I think this is happening because I am forcing the manipulation of the data object when it returns undefined. This is breaking the loading state feature.
EDIT: Forced data object with custom hook useSubreddit(). Commit [ feature ff275a9 ] removed the injection.

**To Reproduce**
1. Go to https://localhost:3000
2. Click on either users or subreddits in the navigation menu on the left
3. Don't blink and see the 404 load into all data sources

**Expected behavior**
When data is loaded the tiles should read "loading"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 105.0.2

### PR DESCRIPTION
**Pull request by xelacast**
## Describe your changes
I incorporated a conditional statement inside of useSubreddit custom hook to check for an undefined data body. If the statement is true the data object is returned with a custom data.error field that represents the same data.error field from the reddit API.
## Issue ticket number and link
#17 
## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? No
- [x] Will this be part of a product update? If yes, please write one phrase about this update. => Data object is fixed with unpredictable data queries.

### CODE REVIEW

**Comment by xelacast** [comment]
You have created the same bug as last time. DO NOT PREDEFINE DATA OR YOU CREATE BUGS ON LOADING STATES. 5/7 tests now fail because the loading state is now 404.

**Comment by xelacast** [comment]
Undid the changes of commit 490c094 and formated undefined data on each component.

File: components/subreddits/subHeader.tsx [hunk 1]
```diff
@@ -12,12 +12,12 @@ const SubHeader = ({ setter, url }) => {
     <div className={styles.container}>
       <div className={styles.info}>
         <h1 data-testid="sub-title">
-          {data.data ? data.data.display_name_prefixed : data.error}
+          {data?.data ? data.data.display_name_prefixed : '404'}
```
Comment (xelacast) [inline components/subreddits/subHeader.tsx:15]: Is this is a hack around the undefined data object? What would the professional do?

**Review by xelacast — COMMENTED** [review]
Code looks good from a second glance. Good work on running tests after almost merging a bug.
